name: WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *"   # runs once a day at midnight UTC
  workflow_dispatch: {}

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
